### ISSUE TITLE
Install requires *exactly* Python 3.6

### ISSUE THREAD

**Issue by carwash** [riksantikvarieambetet/SOCH-download-CLI#7]
If you try to install with a Python version < 3.6, the installer quite rightly refuses.
But if you try to install with a Python version > 3.6, the installer _also_ refuses. This doesn't seem right. Is the downloader really incompatible with Python 3.7?
Only with a Python version of 3.6.x does the install proceed.

**Comment by Abbe98** [comment]
**FIX**
 - Update pipfile to allow Python >= 3.4
