### ISSUE TITLE
Input is not being URL-encoded and therefore queries fail

### ISSUE THREAD

**Issue by carwash** [riksantikvarieambetet/SOCH-download-CLI#8]
`...--action=institution --institution...` can't handle institutions with reserved characters, such as spaces, irrespective of whether they are escaped or not.

Running `pipenv run python soch-download.py --action=institution --institution='The Unstraight Museum' --key=test` results in an error. As does the escaped version, `pipenv run python soch-download.py --action=institution --institution='The%20Unstraight%20Museum' --key=test`.

As a workaround, one can compose the properly-escaped query manually: `pipenv run python soch-download.py --action=query --query='serviceOrganization="The%20Unstraight%20Museum"' --key=test` but that rather defeats the purpose of having a convenience flag such as `--institution` in the first place.

**Comment by Abbe98** [comment]
**FIX**
 - URL encode all input, both for specific actions and for custom queries.
 - Also update the docs for institution. It currently says the abbreviation should be used but that's not the case.

**Comment by Abbe98** [comment]
Turns out that the encoding was not the issue but the missing `"`. Now fixed.
